# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DemoROJA' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
   pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'Firebase'
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  

 # ==========================================================
  # POST INSTALL
  # ==========================================================
  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )


    # ========================================================
    # POD BUILD SETTINGS
    # ========================================================
target.build_configurations.each do |config|

  # Pods must not be code signed.
  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'

  # iOS deployment target
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

  # C++ standard
  config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
  
  # ADD THIS LINE - Explicitly enable C++20 compiler flag
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-std=c++20 -fno-aligned-new'

  # Warnings
  config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'

  config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'

      end

    end

  end

end
